Programming with Python
Day 5

# Programming with Python

### Introduction to NumPy

This section offers a quick tour of the NumPy library for working with multi-dimensional arrays in Python. NumPy (short for Numerical Python) is a library for scientific computing in Python. Most of the scientific libraries, such as SciPy, Scikit-learn, Pandas, and others, are build on top on NumPy.The NumPy array data structure is called `ndarray`, which is short for *n*-dimensional array. 


### N-dimensional Arrays

NumPy is built around [`ndarrays`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) objects, which are high-performance multi-dimensional array data structures. Intuitively, we can think of a one-dimensional NumPy array as a data structure to represent a vector of elements -- you may think of it as a fixed-size Python list where all elements share the same type. Similarly, we can think of a two-dimensional array as a data structure to represent a matrix or a Python list of lists. 

There are many ways to create an 'array', let us start with the familiar list:

In [1]:
import numpy as np

L = [4,2,7,9]
myarray = np.array(L)
myarray


array([4, 2, 7, 9])

In [3]:
myarray[0]

4

In [4]:
L2 = [[1, 2, 3], [4, 5, 6]]
myarray2 = np.array(L2)
myarray2

array([[1, 2, 3],
       [4, 5, 6]])

Using intervals instead of lists, where if two arguments are provided, the first argument represents the start value and the second value defines the stop value:

In [7]:
#np.arange(1,50,5)  #np.arange(start,stop,step)
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.linspace(-1,1,20) #np.linspace(start,stop,#)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

![](./images/numpy-intro/array_1.png)

In [9]:
myarray2[1,1]

5

By default, NumPy infers the type of the array upon construction. Since we passed Python integers to the array, the `ndarray` object `ary2d` should be of type `int64` on a 64-bit machine, which we can confirm by accessing the `dtype` attribute:

In [10]:
myarray2.dtype

dtype('int32')

If we want to construct NumPy arrays of different types, we can pass an argument to the `dtype` parameter of the `array` function, for example `np.int32` to create 32-bit arrays. 

In [12]:
float32_ary = myarray2.astype(np.float64)
float32_ary

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
float32_ary.dtype

dtype('float64')

To return the number of elements in an array, we can use the `size` attribute, as shown below:

In [14]:
print(myarray.size)
print(myarray2.size)

4
6


And the number of dimensions of our array (Intuitively, you may think of *dimensions* as the *rank* of a tensor) can be obtained via the `ndim` attribute:

In [15]:
print(myarray.ndim)
print(myarray2.ndim)

1
2


If we are interested in the number of elements along each array dimension , we can access the `shape` attribute as shown below:

In [16]:
myarray2.shape

(2, 3)

NB: The `shape` is always a tuple. The `shape` of the one-dimensional array only contains a single value:

In [17]:
myarray.shape

(4,)

### Initializing Arrays

This section provides a non-comprehensive list of array construction functions (placeholders). Simple yet useful functions exist to construct arrays containing ones or zeros:

In [24]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Creating arrays of ones or zeros can also be useful as placeholder arrays, in cases where we do not want to use the initial values for computations but want to fill it with other values right away. If we do not need the initial values (for instance, `'0.'` or `'1.'`), there is also `numpy.empty`, which follows the same syntax as `numpy.ones` and `np.zeros`. However, instead of filling the array with a particular value, the `empty` function creates the array with non-sensical values from memory. We can think of `zeros` as a function that creates the array via `empty` and then sets all its values to `0.` -- in practice, a difference in speed is not noticeable, though.  

In [21]:
np.empty((2,5))[1,1]

dtype('float64')

NumPy also comes with functions to create identity matrices and diagonal matrices as `ndarrays` that can be useful in the context of linear algebra -- a topic that we will explore later in this section. 

In [31]:
np.eye(3) # not in Python 2.7!

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.diag((3, 3, 3))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

### Array Indexing

In this section, we will go over the basics of retrieving NumPy array elements via different indexing methods. Simple NumPy indexing and slicing works similar to Python lists, which we will demonstrate in the following code snippet, where we retrieve the first element of a one-dimensional array:

In [22]:
ary = np.array([1, 2, 3])
ary[0]

1

Also, the same Python semantics apply to slicing operations. The following example shows how to fetch the first two elements in `ary`:

In [23]:
ary[:2] # equivalent to ary[0:2]

array([1, 2])

If we work with arrays that have more than one dimension or axis, we separate our indexing or slicing operations by commas as shown in the series of examples below:

In [21]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

ary[0, 0] # upper left

1

In [22]:
ary[-1, -1] # lower right

6

In [23]:
ary[0, 1] # first row, second column

2

In [24]:
ary[0] # entire first row

array([1, 2, 3])

In [25]:
ary[:, 0] # entire first column

array([1, 4])

In [26]:
ary[:, :2] # first two columns

array([[1, 2],
       [4, 5]])

In [27]:
ary[0, 0]

1

### Array Math and Universal Functions

One of the core features of NumPy that makes working with `ndarray` so efficient and convenient is vectorization. While we typically use for-loops if we want to perform arithmetic operations on sequence-like objects, NumPy provides vectorized wrappers for performing element-wise operations implicitly via so-called *ufuncs* -- short for universal functions. 
(see [official documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) for a complete list of ufunc).

To provide an example of a simple ufunc for element-wise addition, consider the following example, where we add a scalar (here: 1) to each element in a nested Python list:

In [26]:
lst = [[1, 2, 3], [4, 5, 6]]

# print(enumerate(lst)) -- to give index and values to element of a list

for row_idx, row_val in enumerate(lst):
    #print(row_idx, row_val)
    for col_idx, col_val in enumerate(row_val):
        #print(col_idx, col_val)
        lst[row_idx][col_idx] += 1
lst

[[2, 3, 4], [5, 6, 7]]

This for-loop approach is very verbose, and we could achieve the same goal more elegantly using list comprehensions:

In [43]:
lst = [[1, 2, 3], [4, 5, 6]]
[[cell + 1 for cell in row] for row in lst]

[[2, 3, 4], [5, 6, 7]]

We can accomplish the same using NumPy's ufunc for element-wise scalar addition as shown below:

In [28]:
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = np.add(ary, 7)
ary

array([[ 8,  9, 10],
       [11, 12, 13]])

The ufuncs for basic arithmetic operations are `add`, `subtract`, `divide`, `multiply`, and `exp` (exponential). However, NumPy uses operator overloading so that we can use mathematical operators (`+`, `-`, `/`, `*`, and `**`) directly:

In [29]:
ary + 4

array([[12, 13, 14],
       [15, 16, 17]])

In [30]:
ary**2

array([[ 64,  81, 100],
       [121, 144, 169]], dtype=int32)

Other useful unary ufuncs are:
    
- `np.mean` (computes arithmetic average)
- `np.std` (computes the standard deviation)
- `np.var` (computes variance)
- `np.sort` (sorts an array)
- `np.argsort` (returns indices that would sort an array)
- `np.min` (returns the minimum value of an array)
- `np.max` (returns the maximum value of an array)
- `np.argmin` (returns the index of the minimum value)
- `np.argmax` (returns the index of the maximum value)
- `np.array_equal` (checks if two arrays have the same shape and elements)

###  Summarizing

Often, we want to compute the sum or product of array element along a given axis. For this purpose, we can use a ufunc's `reduce` operation. By default, `reduce` applies an operation along the first axis (`axis=0`). In the case of a two-dimensional array, we can think of the first axis as the rows of a matrix. Thus, adding up elements along rows yields the column sums of that matrix as shown below:

In [32]:
ary = np.array([[1, 2, 3], 
                [4, 5, 6]])

np.add.reduce(ary,axis = 0) # column sumns

array([5, 7, 9])

To compute the row sums of the array above, we can specify `axis=1`:

In [33]:
np.add.reduce(ary, axis=1) # row sums

array([ 6, 15])

While it can be more intuitive to use `reduce` as a more general operation, NumPy also provides shorthands for specific operations such as `product` and `sum`. For example, `sum(axis=0)` is equivalent to `add.reduce`:

In [35]:
ary.sum(axis=0) # column sums

array([5, 7, 9])

![](./images/numpy-intro/ufunc.png)

As a word of caution, keep in mind that `product` and `sum` both compute the product or sum of the entire array if we do not specify an axis:

In [34]:
ary.sum()

21

### Broadcasting

A topic we glanced over in the previous section is broadcasting. Broadcasting allows us to perform vectorized operations between two arrays even if their dimensions do not match by creating implicit multidimensional grids. You already learned about ufuncs in the previous section where we performed element-wise addition between a scalar and a multidimensional array, which is just one example of broadcasting. 


![](./images/numpy-intro/broadcasting-1.png)

Naturally, we can also perform element-wise operations between arrays of equal dimensions:

In [35]:
ary1 = np.array([1, 2, 3])
ary2 = np.array([4, 5, 6])

ary1 + ary2

array([5, 7, 9])

In contrast to what we are used from linear algebra, we can also add arrays of different shapes. In the example above, we will add a one-dimensional to a two-dimensional array, where NumPy creates an implicit multidimensional grid from the one-dimensional array `ary1`:

In [57]:
ary3 = np.array([[4, 5, 6], 
                 [7, 8, 9]])

ary3 + np.array([3,1,9]) # similarly, ary1 + ary3

array([[ 7,  6, 15],
       [10,  9, 18]])

![](./images/numpy-intro/broadcasting-2.png)

### Vectorize

In [38]:
 def addsubtract(a,b):
        if a > b:
            return a - b 
        else: 
            return a + b


In [53]:
def example(a):
    b =np.sin(a)
    return np.sin(a)+ 100

In [41]:
addsubtract(3,2)

1

In [54]:
example(myarray)

array([ 99.2431975 , 100.90929743, 100.6569866 , 100.41211849])

In [44]:
betterfunc = np.vectorize(addsubtract)


In [47]:

betterfunc([0,3,6,9],[1,3,5,7])

array([1, 6, 1, 2])

### Exercises
See the exercise file













# STOP HERE

### Advanced Indexing -- Memory Views and Copies

In the previous sections, we have used basic indexing and slicing routines. It is important to note that basic integer-based indexing and slicing create so-called *views* of NumPy arrays in memory. Working with views can be highly desirable since it avoids making unnecessary copies of arrays to save memory resources. To illustrate the concept of memory views, let us walk through a simple example where we access the first row in an array, assign it to a variable, and modify that variable:

In [5]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

first_row = ary[0]
first_row += 99
print(first_row)
ary

[100 101 102]


array([[100, 101, 102],
       [  4,   5,   6]])

As we can see in the example above, changing the value of `first_row` also affected the original array. The reason for this is that `ary[0]` created a view of the first row in `ary`, and its elements were then incremented by 99. The same concept applies to slicing operations:

In [6]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

first_row = ary[:1]
first_row += 99
ary

array([[100, 101, 102],
       [  4,   5,   6]])

In [7]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

center_col = ary[:, 1]
center_col += 99
ary

array([[  1, 101,   3],
       [  4, 104,   6]])

If we are working with NumPy arrays, it is always important to be aware that **slicing creates views** -- sometimes it is desirable since it can speed up our code by avoiding to create unnecessary copies in memory. However, in certain scenarios we want force a copy of an array; we can do this via the `copy` method as shown below:

In [26]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

second_row = ary[1].copy()
second_row += 99
print(second_row)
ary.shape

[103 104 105]


(2, 3)

In addition to basic single-integer indexing and slicing operations, NumPy supports advanced indexing routines called *fancy* indexing. Via fancy indexing, we can use tuple or list objects of non-contiguous integer indices to return desired array elements. Since fancy indexing can be performed with non-contiguous sequences, it cannot return a view -- a contiguous slice from memory. Thus, fancy indexing always returns a copy of an array -- it is important to keep that in mind. The following code snippets show some fancy indexing examples:

In [43]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

ary[:, [0, 2]] # first and and last column

array([[1, 3],
       [4, 6]])

In [44]:
this_is_a_copy = ary[:, [0, 2]]
this_is_a_copy += 99
ary

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
ary[:, [2, 0]] # first and and last column

array([[3, 1],
       [6, 4]])

Finally, we can also use Boolean masks for indexing -- that is, arrays of `True` and `False` values. Consider the following example, where we return all values in the array that are greater than 3:

In [46]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])

greater3_mask = ary > 3
greater3_mask

array([[False, False, False],
       [ True,  True,  True]])

Using these masks, we can select elements given our desired criteria:

In [47]:
ary[greater3_mask]

array([4, 5, 6])

We can also chain different selection criteria using the logical *and* operator '&' or the logical *or* operator '|'. The example below demonstrates how we can select array elements that are greater than 3 and divisible by 2:

In [48]:
ary[(ary > 3) & (ary % 2 == 0)]

array([4, 6])

Note that indexing using Boolean arrays is also considered "fancy indexing" and thus returns a copy of the array.

### Random Number Generators

In machine learning and deep learning, we often have to generate arrays of random numbers -- for example, the initial values of our model parameters before optimization. NumPy has a `random` subpackage to create random numbers and samples from a variety of distributions conveniently. Again, I encourage you to browse through the more comprehensive [numpy.random documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html) for a more comprehensive list of functions for random sampling.

To provide a brief overview of the pseudo-random number generators that we will use most commonly, let's start with drawing a random sample from a uniform distribution:

In [24]:
#np.random.seed(9)
np.random.rand(3)

array([0.24810117, 0.08405965, 0.34549864])

In the code snippet above, we first seeded NumPy's random number generator. Then, we drew three random samples from a uniform distribution via `random.rand` in the half-open interval [0, 1). I highly recommend the seeding step in practical applications as well as in research projects, since it ensures that our results are reproducible. If we run our code sequentially -- for example, if we execute a Python script -- it should be sufficient to seed the random number generator only once at the beginning to enforce reproducible outcomes between different runs. However, it is often useful to create separate `RandomState` objects for various parts of our code, so that we can test methods of functions reliably in unit tests. Working with multiple, separate `RandomState` objects can also be useful if we run our code in non-sequential order -- for example if we are experimenting with our code in interactive sessions or Jupyter Notebook environments. 

The example below shows how we can use a `RandomState` object to create the same results that we obtained via `np.random.rand` in the previous code snippet:

In [25]:
rng1 = np.random.RandomState(seed=123)
rng1.rand(3).shape


(3,)

### Reshaping Arrays

In practice, we often run into situations where existing arrays do not have the *right* shape to perform certain computations. We can reshape a one-dimensional array into a two-dimensional one using `reshape` as follows:

In [32]:
ary1d = np.array([1, 2, 3, 4, 5, 6])
ary2d_view = ary1d.reshape(2, 3)
#ary2d_view

In [34]:
a=np.arange(12).reshape(2,2,3)

In [35]:
np.may_share_memory(ary2d_view, a)

False

While we need to specify the desired elements along each axis, we need to make sure that the reshaped array has the same number of elements as the original one. However, we do not need to specify the number elements in each axis; NumPy is smart enough to figure out how many elements to put along an axis if only one axis is unspecified (by using the placeholder `-1`):

In [37]:
ary1d.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
ary1d.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

We can, of course, also use `reshape` to flatten an array:

In [40]:
ary = np.array([[[1, 2, 3],
                [4, 5, 6]]])

ary.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Sometimes, we are interested in merging different arrays. Unfortunately, there is no efficient way to do this without creating a new array, since NumPy arrays have a fixed size. While combining arrays should be avoided if possible -- for reasons of computational efficiency -- it is sometimes necessary. To combine two or more array objects, we can use NumPy's `concatenate` function as shown in the following examples:

In [44]:
ary = np.array([1, 2, 3])

# stack along the first axis (merge rows and add columns)
np.concatenate((ary, ary)) 
#np.concatenate((ary, ary), axis=1) 

array([1, 2, 3, 1, 2, 3])

In [45]:
ary = np.array([[1, 2, 3]])

# stack along the first axis (merge columns and add rows)
np.concatenate((ary, ary), axis=0) 

array([[1, 2, 3],
       [1, 2, 3]])

### Comparison Operators and Masks

 Using comparison operators (such as `<`, `>`, `<=`, and `>=`), we can create a Boolean mask of an array which consists of `True` and `False` elements depending on whether a condition is met in the target array (here: `ary`):

In [47]:
ary = np.array([1, 2, 3, 4])
mask = ary > 2    # name not command!
mask

array([False, False,  True,  True])

One we created such a Boolean mask, we can use it to select certain entries from the target array -- those entries that match the condition upon which the mask was created):

In [49]:
ary[ary<=2]

array([1, 2])

Beyond the selection of elements from an array, Boolean masks can also come in handy when we want to count how many elements in an array meet a certain condition:

In [54]:
mask

array([False, False,  True,  True])

In [55]:
mask.sum()

2

A related, useful function to assign values to specific elements in an array is the `np.where` function. In the example below, we assign a 1 to all values in the array that are greater than 2 -- and 0, otherwise:

In [63]:
np.where(ary > 2, 1, 0)

array([0, 0, 1, 1])

There are also so-called bit-wise operators that we can use to specify more complex selection criteria:

In [64]:
ary = np.array([1, 2, 3, 4])
mask = ary > 2
ary[mask] = 1
ary[~mask] = 0
ary

array([0, 0, 1, 1])

The `~` operator in the example above is one of the logical operators in NumPy:
    
- A: `&`  or `np.bitwise_and`
- Or: `|` or `np.bitwise_or`
- Xor: `^` or `np.bitwise_xor`
- Not: `~` or `np.bitwise_not`

These logical operators allow us to chain an arbitrary number of conditions to create even more "complex" Boolean masks. For example, using the "Or" operator, we can select all elements that are greater than 3 or smaller than 2 as follows:

In [65]:
ary = np.array([1, 2, 3, 4])

(ary > 3) | (ary < 2)

array([ True, False, False,  True])

And, for example, to negate the condition, we can use the `~` operator:

In [66]:
~((ary > 3) | (ary < 2))

array([False,  True,  True, False])

### Linear Algebra with NumPy Arrays

Intuitively, we can think of one-dimensional NumPy arrays as data structures that represent row vectors:

In [67]:
row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

Similarly, we can use two-dimensional arrays to create column vectors:

In [68]:
column_vector = np.array([[1, 2, 3]]).reshape(-1, 1)
column_vector

array([[1],
       [2],
       [3]])

Instead of reshaping a one-dimensional array into a two-dimensional one, we can simply add a new axis as shown below:

In [69]:
row_vector[:, np.newaxis]

array([[1],
       [2],
       [3]])

Note that in this context, `np.newaxis` behaves like `None`:

In [70]:
row_vector[:, None]

array([[1],
       [2],
       [3]])

All three approaches listed above, using `reshape(-1, 1)`, `np.newaxis`, or `None` yield the same results -- all three approaches create views not copies of the `row_vector` array.

As we remember from the Linear Algebra appendix, we can think of a column vector as a matrix consisting only of one column. To perform matrix multiplication between matrices, we learned that number of columns of the left matrix must match the number of rows of the matrix to the right. In NumPy, we can perform matrix multiplication via the `matmul` function:

In [71]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [72]:
np.matmul(matrix, column_vector)

array([[14],
       [32]])

![](./images/numpy-intro/matmul.png)

However, if we are working with matrices and vectors, NumPy can be quite forgiving if the dimensions of matrices and one-dimensional arrays do not match exactly -- thanks to broadcasting. The following example yields the same result as the matrix-column vector multiplication, except that it returns a one-dimensional array instead of a two-dimensional one:

In [73]:
np.matmul(matrix, row_vector)

array([14, 32])

Similarly, we can compute the dot-product between two vectors (here: the vector norm)

In [74]:
np.matmul(row_vector, row_vector)

14

NumPy has a special `dot` function that behaves similar to `matmul` on pairs of one- or two-dimensional arrays -- its underlying implementation is different though, and one or the other can be slightly faster on specific machines and versions of [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms):

In [75]:
np.dot(row_vector, row_vector)

14

In [76]:
np.dot(matrix, row_vector)

array([14, 32])

In [77]:
np.dot(matrix, column_vector)

array([[14],
       [32]])

Similar to the examples above we can use `matmul` or `dot` to multiply two matrices (here: two-dimensional arrays). In this context, NumPy arrays have a handy `transpose` method to transpose matrices if necessary:

In [78]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

![](./images/numpy-intro/transpose.png)

In [79]:
np.matmul(matrix, matrix.transpose())

array([[14, 32],
       [32, 77]])

![](./images/numpy-intro/matmatmul.png)

While `transpose` can be annoyingly verbose for implementing linear algebra operations -- think of [PEP8's](https://www.python.org/dev/peps/pep-0008/) *80 character per line* recommendation -- NumPy has a shorthand for that: `T`:

In [80]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

While this section demonstrates some of the basic linear algebra operations carried out on NumPy arrays that we use in practice, you can find an additional function in the documentation of NumPy's submodule for linear algebra: [`numpy.linalg`](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). If you want to perform a particular linear algebra routine that is not implemented in NumPy, it is also worth consulting the [`scipy.linalg` documentation](https://docs.scipy.org/doc/scipy/reference/linalg.html) -- SciPy is a library for scientific computing built on top of NumPy.

---

I want to mention that there is also a special [`matrix`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) type in NumPy. NumPy `matrix` objects are analogous to NumPy arrays but are restricted to two dimensions. Also, matrices define certain operations differently than arrays; for instance, the `*` operator performs matrix multiplication instead of element-wise multiplication. However, NumPy `matrix` is less popular in the science community compared to the more general array data structure. 

---

# Reading and writing files

In [2]:
f = open("ibrahim.txt","r") # read , write , append

In [3]:
type(f)

_io.TextIOWrapper

In [4]:
f.readline() # read one line

'Yoruba\tKhoisan\tEurop\tChinese\tIndia\n'

In [6]:
#f.readlines() # read all lines

In [7]:
f.close()

In [11]:
import fileinput

Rows = {} 
for line in fileinput.input("ibrahim.txt"):
    data = line.replace("\n", "").split("\t") 
    if fileinput.lineno() > 1: 
        Rows[data[0]] = data[1:] 
    else: 
        pass


In [10]:
#Rows

In [74]:
out = open("newfile.txt","w")
out.write("This is the first line of text ")
out.write("This is still on the first line\n")
out.writelines(["The second line\n", "The Salmon Mousse"])
out.close()

In [77]:
# using with statement 
with open('file_path.txt', 'w') as file: 
    file.write('Python class !') 